all:
  children:
    localhost:
      hosts:
        18.130.224.235:
          ansible_host: ec2-18-130-224-235.eu-west-2.compute.amazonaws.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
          roles_list:
            - oracle-19c
    dev_all:
      children:
        dev_sandbox:
          hosts:
            172.31.21.254:
              ansible_user: ubuntu
              ansible_ssh_private_key_file: /root/.ssh/id_rsa
              roles_list:
                - oracle-19c

